name: Update Dev Quote Image

on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Dev Note Image
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%S")
          sed -i "s/_=[0-9T:-]*/_=$TIMESTAMP/" README.md

          git config user.name "Jugal-Kishor298"
          git config user.email "kravenkishor.ai@gmail.com"
          if git diff --quiet README.md; then
            echo "No changes in README.md"
            exit 0
          fi
          git add README.md
          git commit -m "Update README.md - $(TZ=Asia/Kolkata date +'%Y-%m-%d %H:%M:%S IST')"
          git push
